query InstrumentRefData($ObjectList: [String!]) {
  DerivedContentLipperFundClass(objectIds: $ObjectList) {
    ObjectId
    SwissStampDutyTax {
      AssetTypeDescription
      IssuerDomicileText
      SwissStampDutyFlag
      TaxationComment
      TaxationType
    }
  }
}